#This code generate the KDTree template file that can be directly used.

import numpy as np
import matplotlib.pyplot as plt
import cPickle as pickle
from sklearn.neighbors import KDTree
from scipy.interpolate import splrep, splev
from sedfit.fitter.template import Template

modelDir = "/Users/jinyi/Work/mcmc/Fitter/template/test_grain_model/"
silTList = np.array([0]) #The types of silicate dust.
graTList = np.array([0]) #The types of graphite dust.
sizeList = np.arange(0.1, 1.6, 0.1)

#Obtain the silicate template interpolated list
tckSilList = []
parSilList = []
for sil in silTList:
    tmplDir = modelDir
    for sz in sizeList:
        modelSil = np.loadtxt(tmplDir+"sil/qsohst_sil_a{0}_dat".format(sz))
        wave  = modelSil[:, 0]
        kappa = modelSil[:, 1]
        tck = splrep(wave, kappa)
        tckSilList.append(tck)
        parSilList.append([sil, sz])
kdtSil = KDTree(parSilList)
print("Silicate dust interpolation finishes!")
modelInfo = {
    "type": silTList, #Silicate dust type
    "size": sizeList,
    "wavelength": wave,
}
parFormat = ["type", "size"]
readMe = '''
This silicate template is generated by Yanxia using Mie theory.
The interpolation is tested well!
'''
silDict = {
    "tckList": tckSilList,
    "kdTree": kdtSil,
    "parList": parSilList,
    "modelInfo": modelInfo,
    "parFormat": parFormat,
    "readMe": readMe
}

#Obtain the graphite template interpolated list
tckGraList = []
parGraList = []
for gra in graTList:
    tmplDir = modelDir
    for sz in sizeList:
        modelGra = np.loadtxt(tmplDir+"gra/qsohst_grap_a{0}_dat".format(sz))
        wave  = modelGra[:, 0]
        kappa = modelGra[:, 1]
        tck = splrep(wave, kappa)
        tckGraList.append(tck)
        parGraList.append([gra, sz])
kdtGra = KDTree(parGraList)
print("Graphite dust interpolation finishes!")
modelInfo = {
    "type": graTList, #Silicate dust type
    "size": sizeList,
    "wavelength": wave,
}
parFormat = ["type", "size"]
readMe = '''
This graphite template is generated by Yanxia using Mie theory.
The interpolation is tested well!
'''
graDict = {
    "tckList": tckGraList,
    "kdTree": kdtGra,
    "parList": parGraList,
    "modelInfo": modelInfo,
    "parFormat": parFormat,
    "readMe": readMe
}

#Save the template
templateReadMe = '''
This template file consists two template dicts for silicate and graphite dust
grain. Each of the dicts can be used as input of the Template class in sedfit
package.
'''
dustModel = {
    "Silicate": silDict,
    "Graphite": graDict,
    "readMe": templateReadMe
}
fp = open("/Users/jinyi/Work/mcmc/Fitter/template/dust_grain_kdt.tmplt", "w")
pickle.dump(dustModel, fp)
fp.close()

##Test the KDTree and the interpolation
#For the silicate
for sz in sizeList:
    modelSil = np.loadtxt(tmplDir+"sil/qsohst_sil_a{0}_dat".format(sz))
    wave0  = modelSil[:, 0]
    kappa0 = modelSil[:, 1]
    t = Template(**silDict)
    par = [0, sz-0.01]
    kappa = t(wave0, par)
    print max(abs(kappa-kappa0))
    plt.plot(wave0, kappa, label="{0:.1f}".format(sz))
    plt.plot(wave0, kappa0, ":r")
plt.xscale("log")
plt.yscale("log")
plt.legend(loc="best", fontsize=6)
plt.savefig("dust_sil.png")
plt.show()
#For the graphite
for sz in sizeList:
    modelGra = np.loadtxt(tmplDir+"gra/qsohst_grap_a{0}_dat".format(sz))
    wave0  = modelGra[:, 0]
    kappa0 = modelGra[:, 1]
    t = Template(**graDict)
    par = [0, sz-0.01]
    kappa = t(wave0, par)
    print max(abs(kappa-kappa0))
    plt.plot(wave0, kappa, label="{0:.1f}".format(sz))
    plt.plot(wave0, kappa0, ":r")
plt.xscale("log")
plt.yscale("log")
plt.legend(loc="best", fontsize=6)
plt.savefig("dust_gra.png")
plt.show()
